#!/bin/bash
# Author(s):  MHA-Team
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################
    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'openclaw'
        intport: '18789'
        extport: '18789'
        bridgeport: '18790'
        image: 'openclaw:local'
        repo_path: '/opt/appdata/openclaw/repo'
        repo_url: 'https://github.com/openclaw/openclaw.git'
        repo_branch: 'main'

    # CORE (MANDATORY) ############################################################
    - name: 'Including cron job'
      include_tasks: '/opt/communityapps/apps/_core.yml'

    # LABELS ######################################################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'true'
          traefik.port: '{{intport}}'
          traefik.frontend.auth.forward.address: '{{gauth}}'
          traefik.frontend.rule: 'Host:{{pgrole}}.{{domain.stdout}}{{tldset}}{{cname}}'
          traefik.frontend.headers.SSLHost: '{{domain.stdout}}'
          traefik.frontend.headers.SSLRedirect: 'true'
          traefik.frontend.headers.STSIncludeSubdomains: 'true'
          traefik.frontend.headers.STSPreload: 'true'
          traefik.frontend.headers.STSSeconds: '315360000'
          traefik.frontend.headers.browserXSSFilter: 'true'
          traefik.frontend.headers.contentTypeNosniff: 'true'
          traefik.frontend.headers.customResponseHeaders: 'X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
          traefik.frontend.headers.forceSTSHeader: 'true'

    - name: 'Setting {{pgrole}} Volumes'
      set_fact:
        pg_volumes:
          - '/opt/appdata/{{pgrole}}:/home/node/.openclaw'
          - '/opt/appdata/{{pgrole}}/workspace:/home/node/.openclaw/workspace'

    - name: 'Generating gateway token'
      set_fact:
        openclaw_gateway_token: "{{ lookup('password', '/opt/appdata/openclaw/.gateway_token length=64 chars=hex') }}"
      no_log: true

    - name: 'Setting {{pgrole}} ENV'
      set_fact:
        pg_env:
          HOME: '/home/node'
          TERM: 'xterm-256color'
          OPENCLAW_GATEWAY_TOKEN: '{{openclaw_gateway_token}}'
          OPENCLAW_GATEWAY_BIND: 'lan'
          NPM_CONFIG_PREFIX: '/home/node/.npm-global'
          PATH: '/home/node/.npm-global/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'


    - name: 'Syncing OpenClaw repo'
      git:
        repo: '{{repo_url}}'
        dest: '{{repo_path}}'
        version: '{{repo_branch}}'
        update: true
        force: true

    - name: 'Creating Docker build temp directories'
      file:
        path: '{{item}}'
        state: directory
        mode: '0755'
      with_items:
        - '/tmp/openclaw-docker-config'
        - '/tmp/openclaw-docker-home'

    - name: 'Disabling Docker credential helpers for build'
      copy:
        dest: '/tmp/openclaw-docker-config/config.json'
        content: '{"auths":{"https://index.docker.io/v1/":{}},"credsStore":"","credHelpers":{}}\n'
        mode: '0644'

    - name: 'Building OpenClaw image'
      command: docker --config /tmp/openclaw-docker-config build -t {{image}} -f Dockerfile .
      args:
        chdir: '{{repo_path}}'
      environment:
        DOCKER_CONFIG: '/tmp/openclaw-docker-config'
        DOCKER_AUTH_CONFIG: '{}'
        HOME: '/tmp/openclaw-docker-home'
        XDG_RUNTIME_DIR: '/tmp'
        DOCKER_BUILDKIT: '0'

    # MAIN DEPLOYMENT #############################################################
    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: no
        command: node dist/index.js gateway --bind {{pg_env.OPENCLAW_GATEWAY_BIND}} --port {{intport}} --allow-unconfigured
        published_ports:
          - '{{ports.stdout}}{{extport}}:{{intport}}'
          - '{{ports.stdout}}{{bridgeport}}:{{bridgeport}}'
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - '{{pgrole}}'
        state: started
        labels: '{{pg_labels}}'

##PG-Community
