#!/bin/bash
# Author(s):  MHA-Team
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################
    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'strapi'
        intport: '1337'
        extport: '1337'
        image: 'node:20-alpine'

    # CORE (MANDATORY) ############################################################
    - name: 'Including cron job'
      include_tasks: '/opt/communityapps/apps/_core.yml'

    # LABELS ######################################################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'true'
          traefik.port: '{{intport}}'
          traefik.frontend.auth.forward.address: '{{gauth}}'
          traefik.frontend.rule: 'Host:{{pgrole}}.{{domain.stdout}}{{tldset}}{{cname}}'
          traefik.frontend.headers.SSLHost: '{{domain.stdout}}'
          traefik.frontend.headers.SSLRedirect: 'true'
          traefik.frontend.headers.STSIncludeSubdomains: 'true'
          traefik.frontend.headers.STSPreload: 'true'
          traefik.frontend.headers.STSSeconds: '315360000'
          traefik.frontend.headers.browserXSSFilter: 'true'
          traefik.frontend.headers.contentTypeNosniff: 'true'
          traefik.frontend.headers.customResponseHeaders: 'X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
          traefik.frontend.headers.forceSTSHeader: 'true'

    - name: 'Setting {{pgrole}} Volumes'
      set_fact:
        pg_volumes:
          - '/etc/localtime:/etc/localtime:ro'
          - '/opt/appdata/{{pgrole}}:/srv/app'
          - '{{path.stdout}}:{{path.stdout}}'

    - name: 'Setting {{pgrole}} ENV'
      set_fact:
        pg_env:
          PUID: '1000'
          PGID: '1000'
          TZ: 'Australia/Perth'
          APP_KEYS: 'umLnv4yjsYF1BbfH7NBrT55jjtnEItrElyePkcIPEHo=,mZKLOpevMCpCvN4IhjHQ8KdqLCMS4zoeo80oSnOzxhU=,IZTgRfM4Xx3j6kNxohXv/tGo05632u+IzHuqjlhFZxc=,tyqOBJpAMHJ22oGWjQpuXJGQapF5T2C5Oqw4QPRC6JA='
          API_TOKEN_SALT: 'kaXm5ksKIIHNczjoIAHwwP27OX6gWSmpPDaDqmecxW4='
          ADMIN_JWT_SECRET: 'SzJCBmhQB9UIs2jV8JJdjgKPTDk+g7BZS3lnsuv30J4='
          TRANSFER_TOKEN_SALT: 'G6sf6krNNE0d5xxyOAlwIYXBM5J5uaFPd2J8UuYHQfc='
          JWT_SECRET: 'gNoiMWdA9FgzrYQbG8Hr+q//JKjxyw08vCp2F3Sz2T0='
          NODE_ENV: 'development'
          DATABASE_CLIENT: 'sqlite'
          DATABASE_FILENAME: '/srv/app/data.db'

    # MAIN DEPLOYMENT #############################################################
    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        command: sh -c "apk add --no-cache python3 make g++ && if [ ! -f /srv/app/package.json ]; then cd /srv/app && npx -y create-strapi-app@latest . --quickstart --no-run --skip-cloud; fi && cd /srv/app && NODE_ENV=development npm run develop"
        published_ports:
          - '{{ports.stdout}}{{extport}}:{{intport}}'
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - '{{pgrole}}'
        state: started
        labels: '{{pg_labels}}'
##PG-Community
